### ISSUE TITLE
Ise Host documentation

### ISSUE THREAD

**Issue by steinzi** [CiscoISE/ansible-ise#6] opened 2021-07-23 14:02 UTC
Hi, so spent the better part of the day trying to figure out with the ERS access for the module,
Turns out I needed to specify the port 9060 to the hostname, could you add a reference to the docs so people don't mess this up

Before:
`ise_hostname: myisehost.exampe.com` 🚫
After:
`ise_hostname: 'myisehost.exampe.com:9060'` ✅

The error handling leaves much to be desired, from the playbook output.
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: string indices must be integers
fatal: [myisehost.exampe.com]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

A try-catch block would go a long way
Current: 
.ansible/collections/ansible_collections/cisco/ise/plugins/action/network_device_group_info.py
```
            for item in generator:
                tmp_response = item.response['SearchResult']['resources'] <--- offending line when output is not as expected
                if isinstance(tmp_response, list):
                    response += tmp_response
                else:
                    response.append(tmp_response)
```

Bad exception handling example
```
                try:
                    tmp_response = item.response['SearchResult']['resources']
                except TypeError:
                    print('Oh no you got some weird output from your ise server, go check the ports or enable the (ise_debug: True) arg')
```

#7 

BTW: the ise_debug: True flag is a lifesaver.

**Comment by wastorga** [comment] 2021-07-23 15:24
Hi, @steinzi .

Thank you for reporting an issue.

About the documentation of `ise_hostname`, it is something that we could improve, the collection assumes that your ISE API Gateway is configured and working so the `:9060` should not be needed.

For the error handling of the generators, I will look into it in more detail.

When a new patch version is ready, I will reply here.

**Comment by steinzi** [comment] 2021-07-24 13:43
Thanks @wastorga 
It's just I'm pretty sure 80% + of your users first contact with your playbook will be on a lab ISE instance because no sane person would run a module they found out on the internet agains their prod :D 

I can promise you you'll get a-lot more love if you include the 9060 port info since it's not super clear when you setup ise by yourself for the first time :D 

Anyway, love the module so far :D 
![Alt Text](https://media.giphy.com/media/7aBE32jCr6lOhtuE9v/giphy.gif)

**Comment by chadd123** [comment] 2021-09-15 14:37
I agree with this bug/request.

I struggled with this for days, and reverted to using standard URI module, because I could not get these modules to function properly. I also am working in a dev environment.

Wasn't until i came across this bug posted by @steinzi , that I even realized what the error was caused by.

It is not clear that "the collection assumes that your ISE API Gateway is configured and working so the :9060 should not be needed". If this is the case, it should also be clearly outlined in the documentation.

**Comment by eiddor** [comment] 2021-10-08 17:38
Circling back on this, when I test my playbooks with ISE 3.0, I get this message when I don't append `:9060` with my ISE hostname.

![image](https://user-images.githubusercontent.com/7586731/136599407-9157910c-d8d9-4b47-8ab7-36adbe615364.png)

As far as I can tell, my ERS/API Gateway settings are fine.  There is no "OpenAPI" setting in ISE 3.0 that I can find.  Once I set `:9060` for my ISE host, my playbooks work fine.

ISE 3.1 does not have this issue.

**Comment by wastorga** [comment] 2022-01-20 18:30
Hi, @steinzi, @eiddor, @chadd123.
Since the creation of the issue, there have been many changes to the [README](https://github.com/CiscoISE/ansible-ise#ise-setup).
Please take a look.
If you find them sufficient, we could close the issue.
Otherwise, feel free to reply here.

**Comment by wastorga** [comment] 2022-02-18 16:45
Hi, @steinzi, @eiddor, @chadd123.
Gently reminder to comment. If there is no comment, I will close this the following week.

**Comment by eiddor** [comment] 2022-02-18 16:46
Hey @wastorga - They look good to me!

**Comment by wastorga** [comment] 2022-02-18 16:51
Thanks, @eiddor. It is helpful to have some validation.
I will wait for @steinzi since he was the one who reported the issue.

**Comment by steinzi** [comment] 2022-02-18 20:15
> Thanks, @eiddor. It is helpful to have some validation.
> 
> I will wait for @steinzi since he was the one who reported the issue.

Looks good to me!

**Comment by wastorga** [comment] 2022-02-18 23:31
All right, I am closing this and the related pull request #7 .

**Closed by wastorga** 2022-02-18 23:31 UTC
